name: Deploy mdBook to GitHub Pages

on:
  push:
    branches:
      - main  # Change to 'master' if that's your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install mdBook
        run: |
          curl -LO https://github.com/rust-lang/mdBook/releases/download/v0.4.37/mdbook-v0.4.37-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf mdbook-v0.4.37-x86_64-unknown-linux-gnu.tar.gz
          sudo mv mdbook /usr/local/bin/

      - name: Build the book
        run: mdbook build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book 
